// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrBsXsC_nH1mf_0_w8JDQAKscc_OeAyk',
    appId: '1:1056788178239:web:04ff5dc6a57b4ad2e49f8a',
    messagingSenderId: '1056788178239',
    projectId: 'qrgenerator-eonify',
    authDomain: 'qrgenerator-eonify.firebaseapp.com',
    storageBucket: 'qrgenerator-eonify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8BeuQ15-ggt0fTCkC3FcE9UcaFQuwgA',
    appId: '1:1056788178239:android:8510d5bd7db41833e49f8a',
    messagingSenderId: '1056788178239',
    projectId: 'qrgenerator-eonify',
    storageBucket: 'qrgenerator-eonify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1savp7qI4si5_yz4ZhtMPfMFdSSDadQY',
    appId: '1:1056788178239:ios:74e2623589428c7be49f8a',
    messagingSenderId: '1056788178239',
    projectId: 'qrgenerator-eonify',
    storageBucket: 'qrgenerator-eonify.appspot.com',
    iosClientId: '1056788178239-eimri8mb0ihqlkh2ffrp5a5mj63ubfn6.apps.googleusercontent.com',
    iosBundleId: 'com.eonify.qrgeneratorui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1savp7qI4si5_yz4ZhtMPfMFdSSDadQY',
    appId: '1:1056788178239:ios:74e2623589428c7be49f8a',
    messagingSenderId: '1056788178239',
    projectId: 'qrgenerator-eonify',
    storageBucket: 'qrgenerator-eonify.appspot.com',
    iosClientId: '1056788178239-eimri8mb0ihqlkh2ffrp5a5mj63ubfn6.apps.googleusercontent.com',
    iosBundleId: 'com.eonify.qrgeneratorui',
  );
}
